FROM debian:buster-slim

# This is the default executor image in the terraform orb

ARG TF_VERSION=0.12.0
ARG GCLOUD_VERSION=247.0.0
ARG HELM_VERSION=2.14.0
ENV TF_IN_AUTOMATION=yep

RUN apt-get update && apt-get install -y \
    git \
    ssh \
    tar \
    gzip \
    ca-certificates \
    curl \
    unzip \
    python2 \
    python3 \
    python3-requests \
    python3-pip \
 && rm -rf /var/lib/apt/lists/*

RUN curl -sL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o terraform.zip \
 && unzip terraform.zip \
 && mv terraform /usr/local/bin \
 && rm -rf terraform*

RUN curl -sL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GCLOUD_VERSION}-linux-x86_64.tar.gz -o /opt/google-cloud-sdk.tar.gz \
 && cd /opt; tar -xf google-cloud-sdk.tar.gz \
 && rm google-cloud-sdk.tar.gz
ENV PATH "/opt/google-cloud-sdk/bin:$PATH"

RUN pip3 install awscli

RUN mkdir -p /usr/local/share/terraform/plugin-cache
ENV TF_PLUGIN_CACHE_DIR=/usr/local/share/terraform/plugin-cache

ENTRYPOINT ["/usr/local/bin/terraform"]
